### ISSUE TITLE
Trading Costs

### ISSUE THREAD

**Issue by spencerogden** [pmorissette/bt#129]
Have you considered how to incorporate trading costs into backtests? bt seems like a great start, and I like the structure compared to zipline.

**Comment by atisharma** [comment]
Looking at the code, I think this is implemented, e.g.
`t = bt.Backtest(s1, price, initial_capital=1000000, commissions=(lambda q, p: abs(p * q) * comms) )`

**Comment by magnumw** [comment]
hey @atisharma, 
exactly the commissions function you shared raises the exception that I'm stuck in an infinite loop. Did you/anyone experience this error?
`Exception: Potentially infinite loop detected. This occured while trying to reduce the amount of shares purchased to respect the outlay <= amount rule. This is most likely due to a commission function that outputs a commission that is greater than the amount of cash a short sale can raise.`

**Comment by atisharma** [comment]
Seems to be related to this bug.
https://github.com/pmorissette/bt/issues/131#issuecomment-374909864

**Comment by JordanPlatts** [comment]
I think I fixed the issue in the latest commit but I would like more test cases. I am not convinced it is a full proof solution. If anyone could submit more test cases, that would be great.

You can see my logic a little easier by looking at this latex sheet.
https://www.authorea.com/297725/-gGBFpGpf8jPn68M_XDYyg

**Comment by Kinzowa** [comment]
> Looking at the code, I think this is implemented, e.g.
> `t = bt.Backtest(s1, price, initial_capital=1000000, commissions=(lambda q, p: abs(p * q) * comms) )`

Hello, could you please explain a little how `commissions` is calculated? especially what is the meaning of `lambda q, p: abs(p * q)` 
Thank you
