### ISSUE TITLE
Rounding of positions

### ISSUE THREAD

**Issue by vfilimonov** [pmorissette/bt#13]
Regarding this [part of the code](https://github.com/pmorissette/bt/blob/master/bt/core.py#L863-866) that calculates how much do we need to buy/sell for rebalancing a position:
```
if amount > 0:
    q = math.floor(amount / (self._price * self.multiplier))
else:
    q = math.ceil(amount / (self._price * self.multiplier))
```
I suggest that we have for both of buys (`amount>0`) and sells (`amound<0`)
```
q = math.floor(amount / (self._price * self.multiplier))
```

Suppose we're holding a portfolio and some securities drop in price, so we need to sell other securities to keep the balance. I think it is better to sell more (`math.floor` for negative amount), so we have positive remainder in the `_capital` and all weights sum to a value less than 1, in contrast to selling less  (`math.ceil` for negative amount) and been overdrafted (negative `_capital`) which would result in a sum of all weights greater than 1.

I understand, that in the present logic fees will overdraft us anyway, but I think that this way of rounding should be still more consistent. In particular if we're working with expensive futures or even equities (this is indeed an extreme, but consider [Lindt & Sprüngli](https://finance.yahoo.com/q;_ylt=ArVeq36GYEDktaKS5l_o9eXxVax_;_ylu=X3oDMTFiNGNzNmlnBHBvcwMxMgRzZWMDeWZpU3ltYm9sTG9va3VwUmVzdWx0cwRzbGsDbHNwbmY-?s=LSPN.F): ~60'000 USD per share). 

Phil, what do you think?

**Comment by pmorissette** [comment]
Hey Vladimir,

Thanks again for your input!

This indeed would be more conservative when reducing a long position to raise capital. However, what about short selling? If I remember correctly, that's why I put in ```math.ceil``` for negative amounts.

Anyways, since we can check the current position value, we should change the code so that it is always conservative. If we are currently long and we are reducing, then use ```math.floor``` as mentioned above. However, if we are initially flat or short, then we should use ```math.ceil```.

What do you think?

**Comment by vfilimonov** [comment]
Right, good that we're on the same page here!
