### ISSUE TITLE
opening position using day open, and closing using day close

### ISSUE THREAD

**Issue by kenneththo** [pmorissette/bt#135]
hi Philippe,
whats your recommendation if i need to run backtest in a case where opening the position using Day Open, and  closing using Day Close?

thanks,
ken

**Comment by JordanPlatts** [comment]
I think you should be able to do this by just creating an algo to rebalance at the open and to rebalance at the close. In the morning you would need to specify weights for the day as usual and in the evening go to cash. Take a look at the rebalance algos but make sure to look at the code on github and not from pip because pip hasn't been updated in awhile.

I am going to close this issue but feel free to ask if you have any more questions.
