### ISSUE TITLE
Tree structure and _paper_trade

### ISSUE THREAD

**Issue by vfilimonov** [pmorissette/bt#21]
Hi Phil,

could you please explain how does (and should) tree structure actually work? Do I understand correctly that the actual money is allocated (fees are paid and `_capital` is changed) only at the `Rebalance()` of the parent? If so - why do we change weights of securities and prices of the parent strategy?

For example here's an example of quite unexpected behavior. Below is the same strategy which is backtested stand-alone and as a part of another strategy:
```
data = bt.get('spy,eem', start='2014-01-01')

com = lambda q, p: 10 * abs(q)

mom_s = bt.Strategy('mom_s', [bt.algos.RunMonthly(),
                              bt.algos.SelectAll(),
                              bt.algos.SelectMomentum(1),
                              bt.algos.WeighEqually(),
                              bt.algos.Rebalance()],
                    ['spy', 'eem'])

from copy import deepcopy
mom_s1 = deepcopy(mom_s)

master = bt.Strategy('master', [bt.algos.RunMonthly(),
                                bt.algos.SelectAll(),
                                bt.algos.WeighEqually(),
                                bt.algos.Rebalance()],
                     [mom_s])

t0 = bt.Backtest(mom_s1, data, commissions=com)
r0 = bt.run(t0)

t = bt.Backtest(master, data, commissions=com)
r = bt.run(t)
```
Note I chose quite a substantial commission to make an effect vivid. Also I have here `deepcopy` explicitly, so you can avoid #19 and test it independently from merging #20.

The performance of `master` and `mom_s` differ quite dramatically:
```
ax = r.prices.plot()
r0.prices.plot(color='r', ax=ax)
```
And the reason is commissions that are paid in `mom_s` and ignored in `master`.

So far I don't understand the whole "paper trading" in the `bt.core`, so I don't see how to fix this issue easily. Could you please advise?

**Comment by pmorissette** [comment]
Hey Vlad,

This was indeed a bug. Basically the new commission function was not being passed down the tree. This is now fixed wtih cfc181b. 

Cheers,
Phil

**Comment by vfilimonov** [comment]
Thanks a lot, Phil!

But anyway, what does this `_paper_trade` property responsible for?

**Comment by pmorissette** [comment]
Hey Vlad,

So basically the idea is as follows. When you have a simple strategy where the child nodes are securities, at algo run time, the algos have access to each security's last price (and historical price) to make their decisions ( calculating weights, momentum, etc.)

If we want the same to hold true for strategies of strategies, we need to first run the child strategy. Once it has been run, we will have its latest "price" (equity value). Once we have this information, our Algos in the master strategy will have the latest "prices" to make decisions as discussed above. Once the master has allocated capital according to its AlgoStack, then we can run the child strategies so that they can in turn deploy the capital that was allocated to them.

Basically, on new data:
1. Run child strategies (paper)
2. Run parent strategy
3. Run child strategies (real)

As you can see above, the first child run is done in a paper trading context - basically it just copies the logic of the strategy and runs it as if it was independent. We don't actually want to run the child strategy twice (extra commissions, etc.) so that's why we run a "paper trading" version of it. The only reason we have this paper strategy is to provide us with a price series for the child strategy. We will then be able to use this price series in our algos at the master strategy level.

Hope this makes sense. I'm still not sure if this is the most efficient/best way to go about this - when you get into strategies of strategies, it starts to get complex!

Let me know if you have any other questions,
Phil

**Comment by vfilimonov** [comment]
Philippe, thanks a lot! Now it's all clear. I think it makes perfect sense, and also explains why do you have both "price" and "value" for the strategy, though for single algo-stack they are interchangeable.

**Comment by pmorissette** [comment]
Yes indeed the concept of price and value are different in this context.

Cheers,
Phil
