### ISSUE TITLE
Unexpected position quantity change

### ISSUE THREAD

**Issue by Fractally** [pmorissette/bt#22]
Hi everyone,

I have just tested the new positions property that was added by Vladimir. I printed the entire pandas DataFrame (Backtest.positions) and noticed something strange. The sample strategy that I used consists of SelectAll, SelectMomentum(1), WeighEqually, Rebalance, RunWeekly. I did not use the new delay functionality that was added for SelectMomentum. Three random securities were chosen for the backtest. Attached is a snippet of the DataFrame:
![screenshot-5dr2](https://cloud.githubusercontent.com/assets/11028142/6575231/913de8c4-c735-11e4-9318-9846ab76fce1.png)

The phenomenon occurs throughout the DataFrame content. The positions always decrease a little the day after changing. For example, on 2010-09-08 position 1 was 127802. The day thereafter it is suddenly 127765. The same happens on 2010-09-13 and 2010-09-14.

I might be missing something, but what would cause this change in position quantities?

**Comment by pmorissette** [comment]
Hey @Fractally,

Thanks for reporting.

Just to make sure we are on the same page here, is this similar to what you are doing:

```Python
import bt

data = bt.get('aapl,msft,gs')

s = bt.Strategy('s', [bt.algos.RunWeekly(),
                      bt.algos.SelectAll(), 
                      bt.algos.SelectMomentum(1),
                      bt.algos.WeighEqually(),
                      bt.algos.Rebalance()])
t = bt.Backtest(s, data)
r = bt.run(t)

print t.positions
```

If this is the case, then I am not seeing the change in positions as reported. These are the first few rows I see:

```
             aapl    gs   msft
Date                          
2010-01-04      0     0      0
2010-01-05      0     0      0
2010-01-06      0     0      0
2010-01-07      0     0      0
2010-01-08      0     0      0
2010-01-11      0  6230      0
2010-01-12      0  6230      0
2010-01-13      0  6230      0
2010-01-14      0  6230      0
2010-01-15      0  6230      0
2010-01-19  33556     0      0
2010-01-20  33556     0      0
2010-01-21  33556     0      0
2010-01-22  33556     0      0
2010-01-25  33544     0      0
2010-01-26  33544     0      0
2010-01-27  33544     0      0
2010-01-28  33544     0      0
2010-01-29  33544     0      0
```

Cheers,
Phil

**Comment by Fractally** [comment]
Hi @pmorissette 

Thanks for the quick reply. I'm doing exactly what you did.  What is the reason for the change in positions between 2010-01-22 and 2010-01-25? That is the phenomenon which I was referring to.

**Comment by Fractally** [comment]
It seems that the order of how algos are added to a strategy creates the different behaviour. I somehow missed this information. Is it specified in the docs?

```
s = bt.Strategy('s', [bt.algos.SelectAll(),
	                       bt.algos.SelectMomentum(1),
                               bt.algos.WeighEqually(),
                               bt.algos.Rebalance(), 
                               bt.algos.RunWeekly()])
```

**Comment by pmorissette** [comment]
Hey @Fractally,

To answer your last question, you should always start with the "Run" type of algos. Basically, the Run-type algos will avoid running all the calculation on each day and will only let the stack evaluate when the condition is True (new week in this case). I will add something in the docs pertaining to this effect. 

If you have RunWeekly at the end, then it pretty much isn't doing anything since all the other algos have already run. Think of the algos as a stack. The next Algo in the stack runs if the one before it returns True. RunWeekly returns False (therefore halting the execution of the AlgoStack) unless we are starting a new week. 

As for the changes in quantity, this is basically a rounding error of sorts. The framework currently calculates the commission after determining the amount of shares to buy (since commission depends on number of shares, we have some circularity - for efficiency purposes, the framework currently calculates the quantity first, then the commissions). This can lead to a slightly negative amount of capital in the strategy account, which in turn will lead to a security weight over 100%. Therefore, when we rebalance on day t and we target 100% allocation, we might actually sell a few shares to compensate for this effect. You can examine ```t.weights``` to see what I mean. 

Hope this makes sense,
Phil

**Comment by Fractally** [comment]
Hi @pmorissette 

Thanks for the thorough reply. I understand the working of bt concerning the algo stack better now.

**Comment by pmorissette** [comment]
@Fractally 

My pleasure! Hope you enjoy using **bt**!

Cheers,
Phil
