### ISSUE TITLE
children's parent is not updated if deepcopy is applied

### ISSUE THREAD

**Issue by dennislblog** [pmorissette/bt#259]
https://github.com/pmorissette/bt/blob/a0374336df5cd40cbf0dc78dbc8f7fdde8de32fc/bt/core.py#L102

Hi, I am not familiar with how to properly provide an issue. Can you please check this line of code? I am not sure if this is what you intend to design:

```python
c1, c2 = Node('c1'), Node('c2')
p = Node('p', children=[c1, c2])
p.children['c1'].parent
>> <Node p>
c1.parent
>> <Node c1>
```

Name: bt
Version: 0.2.7
Summary: A flexible backtesting framework for Python
Home-page: https://github.com/pmorissette/bt
Author: Philippe Morissette
Author-email: morissette.philippe@gmail.com
License: UNKNOWN
Location: /home/dennis/.virtualenvs/pytorch/lib/python3.8/site-packages
Requires: pyprind, ffn
Required-by:

**Comment by dennislblog** [comment]
I think I figured it out. I haven't made `c1` pointer redirected to `p['c1']`.

**Comment by ptomecek** [comment]
The reason it does the deep copy is because the framework stores data from evaluation of the data on the nodes (via the attributes _value, _weight, etc). Thus, whenever children are passed to a node, a copy is created so they store their own version of the data, avoiding the case where multiple strategies share the same security instances and over-write each others' data. As a result, as you pointed out, you need to re-assign c1 and c2 based on the parent to get the copy that is relevant to that tree.

The second thing you point out looks like a bug as far as I can tell.
