### ISSUE TITLE
UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.

### ISSUE THREAD

**Issue by DidierRLopes** [pmorissette/bt#300]
Hey,

Whenever I try to `import bt` I get the following error message:
```
UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
```
when trying to do any `plt.show()`.

Do you know what can be the reason for this? Thanks!

**Comment by timkpaine** [comment]
You have installed a subset of the matplotlib code required to render a figure:
https://stackoverflow.com/questions/56656777/userwarning-matplotlib-is-currently-using-agg-which-is-a-non-gui-backend-so

I recommend installing a valid windowing engine, you can install `tk` (which will use `tkinter`/`TkAgg`) or `qt` (install `PyQt5` or `PyQt4` and then matplotlib will use `Qt5Agg`, etc). You may need to reinstall matplotlib afterward, or otherwise follow the matplotlib docs to re-initialize matplotlib's configuration rc file to now use the newly installed backends.

**Comment by DidierRLopes** [comment]
I think the issue is that my default backend is MacOSX, and when I import bt, your module is forcing it to be changed to agg.

I think probably due to this: https://github.com/pmorissette/ffn/blob/0575a43cdfd4d66eb3d8cc638f45d9595e889022/ffn/core.py#L33

**Comment by DidierRLopes** [comment]
@timkpaine

**Comment by ejoc** [comment]
I added fix it adding this line in the code ```%matplotlib inline```
