### ISSUE TITLE
Child strategies are not used

### ISSUE THREAD

**Issue by mikkelbp** [pmorissette/bt#318]
Hi
After updating anaconda and python, my main strategy no longer takes in the child strategies, but just equal-weigh the whole universe...

This is the code:

s77 = bt.Strategy('AI ensemble', [bt.algos.RunAfterDays(n), bt.algos.RunMonthly(),
                        bt.algos.SelectAll(),
                        OrderedWeights([0.25,0.25,0.25,0.25]),
                        bt.algos.Rebalance()],[s1,s2,s4,s5])
test77 = bt.Backtest(s77, all_data)
res77 = bt.run(test77)

Any help is appreciated!

**Comment by samuel-poon** [comment]
Can you post your entire code? What is `OrderedWeights`?

**Comment by mikkelbp** [comment]
The rest of the code i.e. the child strategies are of the same format as the parent and everything worked perfectly until I updated. OrderedWeights is the weights supposed to be assigned to the children strategies. The problem is the same with WeighEqually.

**Comment by MDDietz1** [comment]
Same problem for me. I am not sure what is expected, but using a combined strategy
bt.Strategy(bt.algos.SelectAll(),
bt.algos.PrintInfo(fmt_string='{name} {now} {temp}'),
bt.algos.WeighEqually(),
bt.algos.PrintInfo(fmt_string='{name} {now} {temp}'),
bt.algos.Rebalance()],
children = [strat_1, strat_2])

I see the following:
bt.algos.SelectAll()  selects the full asset universe plus the strategy children that I have declared. 'selected': ['Asset1', 'Asset2', [...] 'Asset8', 'strat_1', 'strat_2']   I would expect it to only select the 2 children [strat_1, strat_2]? All of the assets are "bt.HedgeSecurity" but not sure that matters here.
bt.algos.WeighEqually() then equally weights all selected underlying asset classes plus the children strategies. So instead of getting equal weight across the two children (0.5 each), I get equal weights across all assets plus the children (0.1 for 8 assets and 2 strategies)

**Comment by MDDietz1** [comment]
My workaround is:
bt.Strategy(bt.algos.SelectThese(list([strat_1.name, strat_2.name])),
bt.algos.PrintInfo(fmt_string='{name} {now} {temp}'),
bt.algos.WeighEqually(),
bt.algos.PrintInfo(fmt_string='{name} {now} {temp}'),
bt.algos.Rebalance()],
children = [strat_1, strat_2])
