### ISSUE TITLE
Long one strategy, short another

### ISSUE THREAD

**Issue by JonelaCode** [pmorissette/bt#335]
Hi,

I am new to bt so apologies for a very basic question. I have created two separate strategies without absolutely any issues but I would now like to combine them into one, where I go long one and short the other.

Here are the two strategies I have:
`s_top = bt.Strategy('top', [SelectWhere(signal_top2),
                            bt.algos.RunMonthly(run_on_first_date=True),
                            bt.algos.WeighEqually(), 
                            bt.algos.Rebalance()])

t_top = bt.Backtest(s_top, dfprice2)

s_bottom = bt.Strategy('bottom', [SelectWhere(signal_bottom2),
                                  bt.algos.RunMonthly(run_on_first_date=True),
                                  bt.algos.WeighEqually(), 
                                  bt.algos.Rebalance()])
                                  # bt.algos.Rebalance()

t_bottom = bt.Backtest(s_bottom, dfprice2)

res = bt.run(t_top, t_bottom)`

How would I build a strategy where I go long t_top, short t_bottom, let's even say in equal amounts for each.

Thank you!

**Comment by Socvest** [comment]
You could concatenate both signals but before doing that, you want to multiply signal bottom2, which I am assuming is your short positions, by -1 to reflect the fact that you are going short. Then concat and then run the backtest. But not sure how this will work out without knowing how many assets you have and if you have the same assets in both signals. Please give this information in your code to further clarify. If you have other assets, might have to use 'WeighTarget' instead of 'SelectWhere'.
