### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mosesmc52** [pmorissette/bt#65]
Hi, 

I have been using bt for the past year. It's a really useful backtesting tool. I have a feature update request for the security weight plot. I backtest using  multiple securities. It's difficult for me to see individual trades using the plot_security_weights method.  Could you either update or grate a new method that displays individual security trades each within it's own separate plot. That would be really useful. 

Thanks,

Moses

**Comment by pmorissette** [comment]
Hey @mosesmc52,

Thanks for the feedback. I personally don't have time to implement this, but since you have access to the security weights DataFrame, you could write your own function to plot the data as you see fit. 

Pandas supports plotting multiple subplots (see http://pandas.pydata.org/pandas-docs/stable/visualization.html#subplots for more info). 

If you develop a nice charting function that would be useful for others, please don't hesitate to submit a pull request!

Cheers,
Phil
