### ISSUE TITLE
Sign Issue with Short Positions (?)

### ISSUE THREAD

**Issue by FinQuest** [pmorissette/bt#87]
It looks like there may be a +/- issue somewhere in the code for short positions.

```python
# get data
data = bt.get('aapl', start='2016-01-01', end='2016-03-31')

# Simple single asset strategy rebalancing to -100% once per month
dates = [pd.to_datetime(dte) for dte in ['2016-01-04', '2016-01-29', '2016-02-29']]
weights = pd.DataFrame([-1., -1., -1.], index=dates, columns=data.columns)

short = bt.Strategy('short', [bt.algos.WeighTarget(weights),
                              bt.algos.Rebalance()])                         
                              
# run backtest
bt_short = bt.Backtest(short, data, integer_positions=False, name='short')
result = bt.run(bt_short)

# get trades
result.get_transactions('short')
```

When running the above strategy resetting to 100% short monthly, the strategy leverages up and reinvests exactly double the negative P&L:

```
                          price     quantity
Date       Security                         
2016-01-04 aapl      102.612183 -9745.431495
2016-01-29 aapl       94.810344 -1603.881693
2016-02-29 aapl       94.688268   -29.264000
```

If I look at the security weights for a long position they remain at 1. In this case they are not:

```python
result.backtests['short'].security_weights
```

```
                aapl
2016-01-03  0.000000
2016-01-04 -1.000000
2016-01-05 -0.951107
2016-01-06 -0.915455
2016-01-07 -0.844201
2016-01-08 -0.852471
             ...
2016-03-29 -1.256476
2016-03-30 -1.307086
2016-03-31 -1.291504
```

Not familiar enough with library to try and debug yet and possibly user error!

Thanks,

Tim

**Comment by FinQuest** [comment]
@pmorissette - Any idea on this one Phil?  Cheers,  Tim

**Comment by pmorissette** [comment]
Hey Tim,

Quite busy as of late. I'll have to take a look, but not sure when I will have time.

Cheers,
Phil

**Comment by FinQuest** [comment]
Thanks Phil

**Comment by pmorissette** [comment]
Hey Tim,

As far as I can tell, this is working as expected. Basically, on your rebalance dates, the weights are indeed brought back to -1. 

Short selling is quite different from buying long, and that's why the weights are not always -1, as in the long case. Basically, when you short sell, you receive cash. The proceeds of the short sale are then passed up the tree to the parent strategy. You can see this in `result.backtests['short'].strategy.data`. This DataFrame contains the price index, the value (sum of all children values + cash), cash, and fees. 

Anyways, when the value of the short position changes, this can lead to situations where the weight exceeds -1 because a short sale implicitly creates leverage. Currently, `bt` does not enforce any margin requirements for simplicity's sake (as you would be subject to in 'real life'), but in theory this could be added (forcing you to cover your shorts if you don't have enough cash in your parent strategy). 

Hope this makes sense,
Phil
